//! =============================================================================
//! Memory Node Entity
//! =============================================================================
//! Represents a single memory unit in the GraphRAG system.
//! Each memory is stored as a node in SurrealDB with vector embeddings
//! for semantic search and graph relations for contextual connections.
//! 
//! # GraphRAG Pattern
//! 
//! The Memory Node is the core unit of the Graph Retrieval-Augmented Generation
//! system. It combines:
//! 
//! 1. **Vector Embeddings**: For semantic similarity search
//! 2. **Graph Relations**: For contextual navigation between memories
//! 3. **Metadata**: For filtering and temporal ordering
//! 
//! ```text
//!                    ┌─────────────────┐
//!                    │   MemoryNode    │
//!                    │  ┌───────────┐  │
//!                    │  │  vector[] │  │ ◄── Semantic Search
//!                    │  │  content  │  │
//!                    │  │  metadata │  │
//!                    │  └───────────┘  │
//!                    └────────┬────────┘
//!                             │
//!        ┌────────────────────┼────────────────────┐
//!        │                    │                    │
//!        ▼                    ▼                    ▼
//!   ┌─────────┐         ┌─────────┐         ┌─────────┐
//!   │ Related │         │ Causes  │         │PartOf   │
//!   │ Memory  │         │ Memory  │         │ Memory  │
//!   └─────────┘         └─────────┘         └─────────┘
//! ```
//! =============================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// =============================================================================
/// MemoryNode - Core Memory Entity
/// =============================================================================
/// Represents a single memory unit in the NEURO-OS GraphRAG system.
/// 
/// # Fields
/// 
/// * `id` - Unique identifier for the memory (UUID v4)
/// * `content` - The actual content/text of the memory
/// * `vector` - Vector embedding for semantic search (typically 384-1536 dims)
/// * `memory_type` - Classification of the memory type
/// * `metadata` - Additional metadata (tags, source, importance, etc.)
/// * `created_at` - Timestamp when the memory was created
/// * `updated_at` - Timestamp of the last update
/// * `access_count` - Number of times this memory has been accessed
/// * `importance_score` - Computed importance score (0.0 - 1.0)
/// 
/// # Example
/// 
/// ```rust
/// use neuro_backend::domain::entities::memory::MemoryNode;
/// 
/// let memory = MemoryNode::new(
///     "The user prefers dark mode interfaces".to_string(),
///     vec![0.1, 0.2, 0.3, ...], // embedding vector
///     MemoryType::Preference,
/// );
/// ```
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryNode {
    /// Unique identifier for the memory (UUID v4)
    /// This is used as the primary key in SurrealDB
    pub id: Uuid,

    /// The actual content/text of the memory
    /// This can be a fact, preference, conversation snippet, or any text
    pub content: String,

    /// Vector embedding for semantic search
    /// Generated by the embedding model (e.g., nomic-embed-text)
    /// Dimensions depend on the model used (typically 384, 768, or 1536)
    #[serde(default)]
    pub vector: Vec<f32>,

    /// Classification of the memory type
    /// Used for filtering and specialized retrieval
    pub memory_type: MemoryType,

    /// Additional metadata for the memory
    /// Contains tags, source information, and other attributes
    pub metadata: MemoryMetadata,

    /// Timestamp when the memory was created (UTC)
    pub created_at: DateTime<Utc>,

    /// Timestamp of the last update (UTC)
    pub updated_at: DateTime<Utc>,

    /// Number of times this memory has been accessed/retrieved
    /// Used for computing importance and recency
    #[serde(default)]
    pub access_count: u64,

    /// Computed importance score (0.0 - 1.0)
    /// Based on access frequency, recency, and explicit importance
    #[serde(default)]
    pub importance_score: f64,
}

impl MemoryNode {
    /// =========================================================================
    /// Create a new MemoryNode
    /// =========================================================================
    /// Constructs a new memory node with the provided content, vector, and type.
    /// Automatically generates a UUID and sets timestamps.
    /// 
    /// # Arguments
    /// 
    /// * `content` - The text content of the memory
    /// * `vector` - The embedding vector for semantic search
    /// * `memory_type` - The classification type of the memory
    /// 
    /// # Returns
    /// 
    /// A new `MemoryNode` instance with generated ID and current timestamps
    /// =========================================================================
    pub fn new(content: String, vector: Vec<f32>, memory_type: MemoryType) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            content,
            vector,
            memory_type,
            metadata: MemoryMetadata::default(),
            created_at: now,
            updated_at: now,
            access_count: 0,
            importance_score: 0.5, // Default neutral importance
        }
    }

    /// =========================================================================
    /// Create a MemoryNode with full parameters
    /// =========================================================================
    /// Constructs a memory node with all parameters specified.
    /// Used when loading from database or creating with specific metadata.
    /// 
    /// # Arguments
    /// 
    /// * `id` - The unique identifier
    /// * `content` - The text content
    /// * `vector` - The embedding vector
    /// * `memory_type` - The memory classification
    /// * `metadata` - Additional metadata
    /// 
    /// # Returns
    /// 
    /// A new `MemoryNode` instance with the provided values
    /// =========================================================================
    pub fn with_metadata(
        content: String,
        vector: Vec<f32>,
        memory_type: MemoryType,
        metadata: MemoryMetadata,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            content,
            vector,
            memory_type,
            metadata,
            created_at: now,
            updated_at: now,
            access_count: 0,
            importance_score: 0.5,
        }
    }

    /// =========================================================================
    /// Record an access to this memory
    /// =========================================================================
    /// Increments the access count and recalculates the importance score.
    /// Called whenever this memory is retrieved in a query.
    /// 
    /// # Side Effects
    /// 
    /// * Increments `access_count` by 1
    /// * Recalculates `importance_score` based on new access data
    /// * Updates `updated_at` timestamp
    /// =========================================================================
    pub fn record_access(&mut self) {
        self.access_count += 1;
        self.updated_at = Utc::now();
        self.recalculate_importance();
    }

    /// =========================================================================
    /// Recalculate the importance score
    /// =========================================================================
    /// Computes a new importance score based on:
    /// 
    /// 1. Access frequency (more accesses = more important)
    /// 2. Recency (more recent updates = more relevant)
    /// 3. Explicit importance from metadata
    /// 
    /// # Formula
    /// 
    /// ```text
    /// importance = (access_weight * 0.3) + (recency_weight * 0.3) + (explicit * 0.4)
    /// ```
    /// =========================================================================
    fn recalculate_importance(&mut self) {
        // Access frequency component (logarithmic scaling to prevent runaway)
        let access_weight = (1.0 + self.access_count as f64).ln() / 10.0;
        let access_weight = access_weight.min(1.0);

        // Recency component (decay over time)
        let age_hours = (Utc::now() - self.updated_at).num_hours() as f64;
        let recency_weight = (-age_hours / 168.0).exp(); // Half-life of ~1 week

        // Explicit importance from metadata
        let explicit_importance = self.metadata.explicit_importance.unwrap_or(0.5);

        // Weighted combination
        self.importance_score = (access_weight * 0.3)
            + (recency_weight * 0.3)
            + (explicit_importance * 0.4);

        // Clamp to valid range
        self.importance_score = self.importance_score.clamp(0.0, 1.0);
    }

    /// =========================================================================
    /// Check if the memory vector is populated
    /// =========================================================================
    /// Returns true if the memory has a valid embedding vector.
    /// Memories without vectors cannot participate in semantic search.
    /// =========================================================================
    pub fn has_embedding(&self) -> bool {
        !self.vector.is_empty()
    }
}

/// =============================================================================
/// MemoryType - Classification of Memory Nodes
/// =============================================================================
/// Enum representing the different types of memories that can be stored.
/// This classification helps with filtering and specialized retrieval.
/// =============================================================================
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryType {
    /// Factual information (e.g., "The capital of France is Paris")
    Fact,

    /// User preferences (e.g., "User prefers dark mode")
    Preference,

    /// Procedural knowledge (e.g., "To deploy, run 'cargo build --release'")
    Procedure,

    /// Conversation context (e.g., "User mentioned working on a Rust project")
    Conversation,

    /// General context information (e.g., "Currently working on project X")
    Context,

    /// User-defined semantic tags (e.g., "Project: NEURO-OS")
    SemanticTag,

    /// Error or issue information (e.g., "Build failed due to missing dependency")
    Issue,

    /// Learned patterns or insights
    Insight,

    /// External information from web search
    ExternalKnowledge,

    /// Code snippets or technical documentation
    CodeSnippet,

    /// Tasks, todos, and action items (e.g., "Need to finish report by Friday")
    Task,

    /// Named entities: people, places, organizations, products
    Entity,

    /// Goals and objectives (e.g., "User wants to learn Rust")
    Goal,

    /// Skills and abilities (e.g., "User knows Python")
    Skill,

    /// Events and dates (e.g., "Birthday is on March 15")
    Event,

    /// Opinions and beliefs (e.g., "User thinks AI is the future")
    Opinion,

    /// Experiences and stories (e.g., "User traveled to Japan last year")
    Experience,

    /// Generic/uncategorized memory
    General,
}

impl Default for MemoryType {
    fn default() -> Self {
        Self::General
    }
}

/// =============================================================================
/// MemoryMetadata - Additional Memory Attributes
/// =============================================================================
/// Contains supplementary information about a memory node.
/// Used for filtering, sorting, and providing context.
/// =============================================================================
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MemoryMetadata {
    /// Tags for categorization and filtering
    #[serde(default)]
    pub tags: Vec<String>,

    /// Source of the memory (e.g., "user_input", "web_search", "command_output")
    pub source: Option<String>,

    /// Language of the content (ISO 639-1 code, e.g., "en", "es")
    pub language: Option<String>,

    /// Confidence score for inferred memories (0.0 - 1.0)
    pub confidence: Option<f64>,

    /// Explicit importance set by user or system (0.0 - 1.0)
    pub explicit_importance: Option<f64>,

    /// Reference to related conversation ID
    pub conversation_id: Option<Uuid>,

    /// Reference to related task ID
    pub task_id: Option<Uuid>,

    /// Custom key-value pairs for extensibility
    #[serde(default)]
    pub custom: std::collections::HashMap<String, serde_json::Value>,
}

impl MemoryMetadata {
    /// =========================================================================
    /// Create metadata with tags
    /// =========================================================================
    pub fn with_tags(tags: Vec<String>) -> Self {
        Self {
            tags,
            ..Default::default()
        }
    }

    /// =========================================================================
    /// Add a tag to the metadata
    /// =========================================================================
    pub fn add_tag(&mut self, tag: String) {
        if !self.tags.contains(&tag) {
            self.tags.push(tag);
        }
    }

    /// =========================================================================
    /// Set the source of the memory
    /// =========================================================================
    pub fn with_source(mut self, source: &str) -> Self {
        self.source = Some(source.to_string());
        self
    }

    /// =========================================================================
    /// Set explicit importance
    /// =========================================================================
    pub fn with_importance(mut self, importance: f64) -> Self {
        self.explicit_importance = Some(importance.clamp(0.0, 1.0));
        self
    }
}

/// =============================================================================
/// MemoryQuery - Query parameters for memory retrieval
/// =============================================================================
/// Represents the parameters for querying memories from the database.
/// Supports semantic search, filtering, and pagination.
/// =============================================================================
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MemoryQuery {
    /// Text query for semantic search (will be embedded)
    pub query_text: Option<String>,

    /// Pre-computed query vector (if already embedded)
    pub query_vector: Option<Vec<f32>>,

    /// Filter by memory types
    #[serde(default)]
    pub memory_types: Vec<MemoryType>,

    /// Filter by tags (AND logic)
    #[serde(default)]
    pub tags: Vec<String>,

    /// Minimum importance score
    pub min_importance: Option<f64>,

    /// Maximum number of results to return
    pub limit: Option<usize>,

    /// Number of results to skip (for pagination)
    pub offset: Option<usize>,

    /// Minimum similarity score for semantic search (0.0 - 1.0)
    pub min_similarity: Option<f64>,

    /// Include memories created after this timestamp
    pub created_after: Option<DateTime<Utc>>,

    /// Include memories created before this timestamp
    pub created_before: Option<DateTime<Utc>>,
}

impl MemoryQuery {
    /// =========================================================================
    /// Create a semantic search query
    /// =========================================================================
    pub fn semantic(query_text: String) -> Self {
        Self {
            query_text: Some(query_text),
            limit: Some(10),
            min_similarity: Some(0.7),
            ..Default::default()
        }
    }

    /// =========================================================================
    /// Create a query with type filter
    /// =========================================================================
    pub fn by_type(memory_type: MemoryType) -> Self {
        Self {
            memory_types: vec![memory_type],
            limit: Some(50),
            ..Default::default()
        }
    }

    /// =========================================================================
    /// Set the result limit
    /// =========================================================================
    pub fn with_limit(mut self, limit: usize) -> Self {
        self.limit = Some(limit);
        self
    }

    /// =========================================================================
    /// Set minimum similarity threshold
    /// =========================================================================
    pub fn with_min_similarity(mut self, min_similarity: f64) -> Self {
        self.min_similarity = Some(min_similarity.clamp(0.0, 1.0));
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_memory_node_creation() {
        let memory = MemoryNode::new(
            "Test content".to_string(),
            vec![0.1, 0.2, 0.3],
            MemoryType::Fact,
        );

        assert!(!memory.id.is_nil());
        assert_eq!(memory.content, "Test content");
        assert_eq!(memory.vector.len(), 3);
        assert_eq!(memory.memory_type, MemoryType::Fact);
        assert!(memory.has_embedding());
    }

    #[test]
    fn test_memory_access_tracking() {
        let mut memory = MemoryNode::new(
            "Test content".to_string(),
            vec![0.1, 0.2, 0.3],
            MemoryType::Fact,
        );

        assert_eq!(memory.access_count, 0);
        memory.record_access();
        assert_eq!(memory.access_count, 1);
        memory.record_access();
        assert_eq!(memory.access_count, 2);
    }

    #[test]
    fn test_memory_without_embedding() {
        let memory = MemoryNode::new(
            "Test content".to_string(),
            vec![],
            MemoryType::General,
        );

        assert!(!memory.has_embedding());
    }
}
