/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/graph/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * =============================================================================
         * @description Export full graph (for visualization)
         *     =============================================================================
         *     GET /api/admin/graph/export
         *     =============================================================================
         */
        get: operations["export_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/graph/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * =============================================================================
         * @description Get graph statistics
         *     =============================================================================
         *     GET /api/admin/graph/stats
         *     =============================================================================
         */
        get: operations["get_graph_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/agent/execute */
        post: operations["execute_command"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/agent/search */
        post: operations["web_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/chat */
        post: operations["send_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/chat/conversations */
        get: operations["list_conversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * =============================================================================
         * @description Health check
         *     =============================================================================
         *     GET /api/health
         *     =============================================================================
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/llm/chat
         * @description Non-streaming chat completion with message history
         */
        post: operations["llm_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/llm/embed
         * @description Generate embedding for a single text
         */
        post: operations["llm_embed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /api/llm/generate
         * @description Raw text generation from a prompt
         */
        post: operations["llm_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /api/llm/health
         * @description Returns detailed health status of the LLM provider (Ollama)
         */
        get: operations["llm_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/memories */
        get: operations["list_memories"];
        put?: never;
        /** POST /api/memories */
        post: operations["create_memory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/memories/search */
        post: operations["search_memories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/memories/:id */
        get: operations["get_memory"];
        put?: never;
        post?: never;
        /** DELETE /api/memories/:id */
        delete: operations["delete_memory"];
        options?: never;
        head?: never;
        /** PATCH /api/memories/:id */
        patch: operations["update_memory"];
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * =============================================================================
         * @description GET /api/models
         *     =============================================================================
         */
        get: operations["list_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * =============================================================================
         * @description Get system info
         *     =============================================================================
         *     GET /api/system/info
         *     =============================================================================
         */
        get: operations["system_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Build information for identifying compiled binary */
        BuildInfoDto: {
            /** @description Build timestamp */
            build_time: string;
            /** @description Git commit hash (short) */
            git_hash: string;
            /** @description Rust version used */
            rust_version: string;
        };
        /**
         * @description =============================================================================
         *     ChatMessage - Message in a conversation
         *     =============================================================================
         */
        ChatMessage: {
            content: string;
            role: string;
        };
        /** @description Chat message DTO */
        ChatMessageDto: {
            /** @description Message content */
            content: string;
            /** @description Created timestamp */
            created_at: string;
            /**
             * Format: uuid
             * @description Message ID
             */
            id: string;
            /** @description Model used (for assistant messages) */
            model?: string | null;
            /** @description Message role (user, assistant, system) */
            role: string;
            /**
             * Format: int64
             * @description Tokens in completion
             */
            tokens_completion?: number | null;
            /**
             * Format: int64
             * @description Tokens in prompt
             */
            tokens_prompt?: number | null;
        };
        /**
         * @description =============================================================================
         *     Chat DTOs
         *     =============================================================================
         *     Chat message request
         */
        ChatMessageRequest: {
            /**
             * Format: uuid
             * @description Optional conversation ID (creates new if not provided)
             */
            conversation_id?: string | null;
            /** @description User message content */
            message: string;
            /** @description Whether to stream the response */
            stream?: boolean;
            /** @description Optional system prompt override */
            system_prompt?: string | null;
        };
        /** @description Chat message response */
        ChatMessageResponse: {
            /** @description Response content */
            content: string;
            /**
             * Format: uuid
             * @description Conversation ID
             */
            conversation_id: string;
            /** @description Memories extracted from conversation */
            extracted_memories?: components["schemas"]["MemoryDto"][];
            /**
             * Format: uuid
             * @description Message ID
             */
            message_id: string;
            /** @description Model used for generation */
            model: string;
            /**
             * Format: int64
             * @description Processing time in milliseconds
             */
            processing_time_ms: number;
            /**
             * Format: int64
             * @description Tokens in completion
             */
            tokens_completion: number;
            /**
             * Format: int64
             * @description Tokens used in prompt
             */
            tokens_prompt: number;
            /** @description Tools used during processing */
            tools_used?: string[];
        };
        ChatRequest: {
            messages: components["schemas"]["ChatMessage"][];
            model?: string | null;
        };
        /** @description Command execution request */
        CommandExecuteRequest: {
            /** @description Command to execute */
            command: string;
            /**
             * Format: int64
             * @description Optional timeout in seconds
             */
            timeout_seconds?: number | null;
            /** @description Optional working directory */
            working_directory?: string | null;
        };
        /** @description Command execution result */
        CommandResultDto: {
            /**
             * Format: int64
             * @description Execution duration in ms
             */
            duration_ms: number;
            /**
             * Format: int32
             * @description Exit code
             */
            exit_code: number;
            /** @description Standard error */
            stderr: string;
            /** @description Standard output */
            stdout: string;
            /** @description Whether command timed out */
            timed_out: boolean;
        };
        /** @description Conversation summary */
        ConversationDto: {
            /** @description Created timestamp */
            created_at: string;
            /**
             * Format: uuid
             * @description Conversation ID
             */
            id: string;
            /** @description Message count */
            message_count: number;
            /** @description Conversation title */
            title: string;
            /** @description Last updated timestamp */
            updated_at: string;
        };
        /** @description Full conversation with messages */
        ConversationWithMessagesDto: {
            /** @description Created timestamp */
            created_at: string;
            /**
             * Format: uuid
             * @description Conversation ID
             */
            id: string;
            /** @description Messages in the conversation */
            messages: components["schemas"]["ChatMessageDto"][];
            /** @description Conversation title */
            title: string;
            /** @description Last updated timestamp */
            updated_at: string;
        };
        /** @description Create memory request */
        CreateMemoryRequest: {
            /** @description Memory content */
            content: string;
            /**
             * Format: double
             * @description Optional importance score
             */
            importance_score?: number | null;
            /** @description Memory type */
            memory_type?: string;
            /** @description Optional metadata */
            metadata?: unknown;
        };
        /** @description Create relation request */
        CreateRelationRequest: {
            /**
             * Format: double
             * @description Optional confidence score (defaults to 1.0)
             */
            confidence?: number;
            /**
             * Format: uuid
             * @description Source memory ID
             */
            from_id: string;
            /** @description Relation type */
            relation: string;
            /**
             * Format: uuid
             * @description Target memory ID
             */
            to_id: string;
        };
        EmbedRequest: {
            text: string;
        };
        EmbedResponse: {
            dimensions: number;
            embedding: number[];
        };
        /** @description API error response */
        ErrorResponse: {
            /** @description Error code */
            code: string;
            /** @description Optional details */
            details?: unknown;
            /** @description Error message */
            message: string;
        };
        GenerateRequest: {
            model?: string | null;
            prompt: string;
        };
        GenerateResponse: {
            /** Format: int64 */
            completion_tokens: number;
            content: string;
            model: string;
            /** Format: int64 */
            prompt_tokens: number;
        };
        /**
         * @description =============================================================================
         *     Graph DTOs
         *     =============================================================================
         *     Graph edge response
         */
        GraphEdgeDto: {
            /**
             * Format: double
             * @description Confidence score
             */
            confidence: number;
            /** @description Created timestamp */
            created_at: string;
            /**
             * Format: uuid
             * @description Source memory ID
             */
            from_id: string;
            /** @description Relation type */
            relation: string;
            /**
             * Format: uuid
             * @description Target memory ID
             */
            to_id: string;
        };
        /** @description Full graph export response */
        GraphExportDto: {
            /** @description All edges */
            edges: components["schemas"]["GraphEdgeDto"][];
            /** @description Export timestamp */
            exported_at: string;
            /** @description All nodes */
            nodes: components["schemas"]["MemoryDto"][];
        };
        /** @description Graph statistics response */
        GraphStatsDto: {
            /**
             * Format: double
             * @description Average connections per node
             */
            avg_connections: number;
            /** @description Edges by type */
            edges_by_type: {
                [key: string]: number;
            };
            /** @description Nodes by type */
            nodes_by_type: {
                [key: string]: number;
            };
            /** @description Total number of edges */
            total_edges: number;
            /** @description Total number of nodes */
            total_nodes: number;
        };
        /**
         * @description =============================================================================
         *     System DTOs
         *     =============================================================================
         *     Health check response
         */
        HealthResponse: {
            build_info: components["schemas"]["BuildInfoDto"];
            services: components["schemas"]["ServiceStatusDto"];
            /** @description Overall status */
            status: string;
            /**
             * Format: int64
             * @description Uptime in seconds
             */
            uptime_seconds: number;
            /** @description Version info */
            version: string;
        };
        /**
         * @description =============================================================================
         *     LlmHealthStatus - Detailed health status
         *     =============================================================================
         */
        LlmHealthStatus: {
            /** @description Error message if unhealthy */
            error?: string | null;
            /** @description Is the provider reachable */
            healthy: boolean;
            /** @description List of available models */
            models: string[];
            /** @description Number of models available */
            models_count: number;
            /** @description Provider URL */
            provider_url: string;
        };
        /**
         * @description =============================================================================
         *     Memory DTOs
         *     =============================================================================
         *     Memory node response
         */
        MemoryDto: {
            /**
             * Format: int64
             * @description Access count
             */
            access_count: number;
            /** @description Memory content */
            content: string;
            /** @description Created timestamp */
            created_at: string;
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /**
             * Format: double
             * @description Importance score (0.0 - 1.0)
             */
            importance_score: number;
            /** @description Memory type */
            memory_type: string;
            /** @description Metadata */
            metadata?: unknown;
            /** @description Updated timestamp */
            updated_at: string;
        };
        /** @description Model info response */
        ModelInfoDto: {
            /** @description Context length */
            context_length?: number | null;
            /** @description Model identifier */
            id: string;
            /** @description Is embedding model */
            is_embedding_model: boolean;
            /** @description Model name */
            name: string;
            /**
             * Format: int64
             * @description Parameter count
             */
            parameters?: number | null;
            /**
             * Format: int64
             * @description Size in bytes
             */
            size_bytes?: number | null;
        };
        /** @description Search result */
        SearchResultDto: {
            memory: components["schemas"]["MemoryDto"];
            /**
             * Format: double
             * @description Similarity score
             */
            similarity: number;
        };
        /** @description Semantic search request */
        SemanticSearchRequest: {
            /** @description Maximum results to return */
            limit?: number;
            /** @description Optional memory type filter */
            memory_types?: string[] | null;
            /**
             * Format: double
             * @description Minimum similarity score (0.0 - 1.0)
             */
            min_similarity?: number;
            /** @description Search query */
            query: string;
        };
        /** @description Service status details */
        ServiceStatusDto: {
            /** @description Database status */
            database: string;
            /** @description LLM provider status */
            llm: string;
            /** @description Search provider status */
            search: string;
        };
        SystemInfoDto: {
            memory_count: number;
            rust_version: string;
            total_edges: number;
            /** Format: int64 */
            uptime_seconds: number;
            version: string;
        };
        /** @description Update memory request */
        UpdateMemoryRequest: {
            /** @description New content (optional) */
            content?: string | null;
            /**
             * Format: double
             * @description New importance score (optional)
             */
            importance_score?: number | null;
            /** @description New metadata (optional) */
            metadata?: unknown;
        };
        /**
         * @description =============================================================================
         *     Agent DTOs
         *     =============================================================================
         *     Web search request
         */
        WebSearchRequest: {
            /** @description Category filter */
            category?: string | null;
            /** @description Maximum results */
            limit?: number;
            /** @description Search query */
            query: string;
        };
        /** @description Web search result */
        WebSearchResultDto: {
            /**
             * Format: double
             * @description Optional score
             */
            score?: number | null;
            /** @description Result snippet */
            snippet: string;
            /** @description Source engine */
            source: string;
            /** @description Result title */
            title: string;
            /** @description Result URL */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    export_graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full graph export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphExportDto"];
                };
            };
            /** @description Export error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_graph_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Graph statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphStatsDto"];
                };
            };
            /** @description Database error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    execute_command: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandExecuteRequest"];
            };
        };
        responses: {
            /** @description Command executed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResultDto"];
                };
            };
            /** @description Execution error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Command not allowed */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Check error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    web_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebSearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebSearchResultDto"][];
                };
            };
            /** @description Search error */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    send_message: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Chat response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            /** @description Chat error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_conversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDto"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    llm_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Chat completion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Chat error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    llm_embed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedRequest"];
            };
        };
        responses: {
            /** @description Embedding generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedResponse"];
                };
            };
            /** @description Embedding error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    llm_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Text generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Generation error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    llm_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LLM provider health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmHealthStatus"];
                };
            };
        };
    };
    list_memories: {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number | null;
                /** @description Items per page */
                per_page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of memories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDto"][];
                };
            };
            /** @description Database error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_memory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemoryRequest"];
            };
        };
        responses: {
            /** @description Memory created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Create error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_memories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultDto"][];
                };
            };
            /** @description Search error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_memory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Memory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Database error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_memory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Memory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Delete error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_memory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemoryRequest"];
            };
        };
        responses: {
            /** @description Memory updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryDto"];
                };
            };
            /** @description Memory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Update error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfoDto"][];
                };
            };
            /** @description LLM provider unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    system_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoDto"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
