//! =============================================================================
//! LLM Provider Port - Complete Interface
//! =============================================================================
//! Defines the abstract interface for Large Language Model operations.
//! This is the ONLY gateway to Ollama - all services must use this interface.
//! =============================================================================

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;

use crate::domain::errors::DomainError;

/// =============================================================================
/// ChatMessage - Message in a conversation
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessage {
    pub role: String,
    pub content: String,
}

impl ChatMessage {
    pub fn user(content: impl Into<String>) -> Self {
        Self { role: "user".to_string(), content: content.into() }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Self { role: "assistant".to_string(), content: content.into() }
    }

    pub fn system(content: impl Into<String>) -> Self {
        Self { role: "system".to_string(), content: content.into() }
    }
}

/// =============================================================================
/// StreamChunk - Chunk of streaming response
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum StreamChunk {
    /// Start of generation
    Start { model: String },
    /// Token/text chunk
    Token { content: String },
    /// Generation complete
    Done { 
        prompt_tokens: u64, 
        completion_tokens: u64,
        finish_reason: String,
    },
    /// Error during generation
    Error { message: String },
}

/// =============================================================================
/// SpeculativeChunk - Chunk from speculative decoding
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SpeculativeChunk {
    /// Start of speculative generation
    Start { 
        draft_model: String, 
        target_model: String,
        lookahead: usize,
    },
    /// Accepted tokens to display
    Tokens { content: String },
    /// Generation complete with stats
    Done { stats: SpeculativeStats },
    /// Error occurred
    Error { message: String },
}

/// =============================================================================
/// SpeculativeStats - Statistics from speculative decoding
/// =============================================================================
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SpeculativeStats {
    /// Total tokens generated by draft model
    pub draft_tokens_generated: usize,
    /// Tokens accepted by target model
    pub tokens_accepted: usize,
    /// Tokens rejected by target model
    pub tokens_rejected: usize,
    /// Acceptance rate (accepted / draft_generated)
    pub acceptance_rate: f32,
    /// Draft model used
    pub draft_model: String,
    /// Target model used
    pub target_model: String,
    /// Number of draft-verify iterations
    pub iterations: usize,
}

/// =============================================================================
/// LlmHealthStatus - Detailed health status
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmHealthStatus {
    /// Is the provider reachable
    pub healthy: bool,
    /// Number of models available
    pub models_count: usize,
    /// List of available models
    pub models: Vec<String>,
    /// Provider URL
    pub provider_url: String,
    /// Error message if unhealthy
    pub error: Option<String>,
}

/// =============================================================================
/// LlmProvider - Abstract interface for LLM operations
/// =============================================================================
/// This is the ONLY interface to communicate with Ollama.
/// All microservices (neuro-chat, neuro-memory, etc.) MUST use this provider
/// through the backend API endpoints.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    // =========================================================================
    // Basic Generation
    // =========================================================================

    /// Generate text completion from a simple prompt
    async fn generate(&self, prompt: &str, model: Option<&str>) -> Result<GenerationResult, DomainError>;

    /// Generate streaming completion (simplified - returns full result)
    async fn generate_stream(&self, prompt: &str, model: Option<&str>) -> Result<GenerationResult, DomainError> {
        self.generate(prompt, model).await
    }

    // =========================================================================
    // Chat (with message history)
    // =========================================================================

    /// Chat completion with message history
    async fn chat(&self, messages: Vec<ChatMessage>, model: Option<&str>) -> Result<GenerationResult, DomainError>;

    /// Stream chat response chunks via channel
    async fn chat_stream(
        &self,
        messages: Vec<ChatMessage>,
        model: Option<&str>,
        tx: mpsc::Sender<StreamChunk>,
    );

    // =========================================================================
    // Speculative Decoding
    // =========================================================================

    /// Speculative decoding with draft and target models
    /// Uses Light tier as draft, Standard/Heavy as target by default
    async fn speculative_stream(
        &self,
        messages: Vec<ChatMessage>,
        draft_model: Option<&str>,
        target_model: Option<&str>,
        lookahead: Option<usize>,
        tx: mpsc::Sender<SpeculativeChunk>,
    );

    /// Generate specific number of tokens (used internally for speculative)
    async fn generate_tokens(
        &self,
        prompt: &str,
        model: &str,
        num_tokens: i32,
    ) -> Result<String, DomainError>;

    // =========================================================================
    // Embeddings
    // =========================================================================

    /// Generate text embedding
    async fn embed(&self, text: &str) -> Result<Vec<f32>, DomainError>;

    /// Generate embeddings for multiple texts
    async fn embed_batch(&self, texts: &[String]) -> Result<Vec<Vec<f32>>, DomainError>;

    // =========================================================================
    // Model Management
    // =========================================================================

    /// Check if a model is available
    async fn is_model_available(&self, model_name: &str) -> bool;

    /// List available models
    async fn list_models(&self) -> Result<Vec<ModelInfo>, DomainError>;

    /// Pull/download a model
    async fn pull_model(&self, model_name: &str) -> Result<(), DomainError>;

    // =========================================================================
    // Health
    // =========================================================================

    /// Check provider health (simple)
    async fn health_check(&self) -> Result<bool, DomainError>;

    /// Get detailed health status
    async fn health_status(&self) -> Result<LlmHealthStatus, DomainError>;
}

/// =============================================================================
/// GenerationResult - Result of text generation
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerationResult {
    /// The generated text
    pub content: String,
    /// Model that was used
    pub model: String,
    /// Number of tokens in the prompt
    pub prompt_tokens: u64,
    /// Number of tokens generated
    pub completion_tokens: u64,
    /// Finish reason
    pub finish_reason: String,
}

/// =============================================================================
/// ModelInfo - Information about an available model
/// =============================================================================
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelInfo {
    /// Model name/identifier
    pub name: String,
    /// Model size in bytes
    pub size: u64,
    /// When the model was modified
    pub modified_at: String,
    /// Parameter count estimate
    pub parameters: Option<u64>,
    /// Whether this is an embedding model
    pub is_embedding: bool,
}
